version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    platform: linux/arm64
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      TZ: "Europe/Kyiv"
      FTLCONF_webserver_api_password: "5K!27dwVt%w*"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: unbound # ← Uses Docker service name, port 53 by default
    volumes:
      - "/opt/pihole/etc-pihole:/etc/pihole"
      - "/opt/pihole/dnsmasq:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: klutchell/unbound
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "dnssec.works", "A"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
