services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp" # Use 8080:80/tcp if you have another service running on port 80
      - "8443:443/tcp"
    environment:
      TZ: "Europe/Kyiv" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      FTLCONF_webserver_api_password: "5K!27dwVt%w*"
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - "/opt/pihole/etc-pihole:/etc/pihole"
    restart: unless-stopped
